# Generated by Django 4.2.3 on 2023-08-11 07:43

from django.db import migrations, models
import shops.serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('social', models.JSONField(default=shops.serializer.social_default_value)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shops')),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
                'ordering': ('city',),
            },
        ),
    ]
